# Navigation Links
main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 20
  - name: People
    url: /people/
    weight: 30
  - name: Publications
    url: /publications/
    weight: 40
  - name: News
    url: /#news
    weight: 50
  - name: Join
    url: /join/
    weight: 60
